// Sample data for the LMS

export const userData = {
  id: 1,
  name: "Zabby",
  email: "Zabby@example.com",
  avatar: "/placeholder.svg",
  role: "Student",
  level: 20,
  points: 88,
  maxPoints: 15,
}

export const courseData = [
  {
    id: 1,
    title: "Advance Networking",
    description: "Learn advanced networking concepts and protocols",
    subtitle: "Course code IT 370 - Section code IT32",
    image: "/placeholder.svg?height=200&width=400",
    color: "bg-blue-700",
    instructor: "Dr. Smith",
    progress: 65,
  },
  {
    id: 2,
    title: "Computer Studies Life Skills Development Program",
    description: "Develop essential life skills for computer science professionals",
    subtitle: "SY 2024-2025",
    image: "/placeholder.svg?height=200&width=400",
    color: "bg-pink-500",
    instructor: "Prof. Johnson",
    progress: 42,
  },
  {
    id: 3,
    title: "Elements of Research - IT32",
    description: "Learn research methodologies and techniques for IT projects",
    subtitle: "",
    image: "/placeholder.svg?height=200&width=400",
    color: "bg-blue-700",
    instructor: "Dr. Williams",
    progress: 78,
  },
  {
    id: 4,
    title: "Guidelines for Taking the Summative Exams",
    description: "Important information about upcoming summative examinations",
    subtitle: "",
    image: "/placeholder.svg?height=200&width=400",
    color: "bg-gray-700",
    instructor: "Academic Affairs",
    progress: 100,
  },
  {
    id: 5,
    title: "INFORMATION MANAGEMENT",
    description: "Learn about information systems and database management",
    subtitle: "",
    image: "/placeholder.svg?height=200&width=400",
    color: "bg-green-700",
    instructor: "Prof. Garcia",
    progress: 35,
  },
  {
    id: 6,
    title: "IT 170 Computer Fundamentals and Operations",
    description: "Introduction to computer systems and operations",
    subtitle: "",
    image: "/placeholder.svg?height=200&width=400",
    color: "bg-blue-700",
    instructor: "Dr. Chen",
    progress: 50,
  },
  {
    id: 7,
    title: "IT 31 - IT 381 - Application Development and Emerging Technologies",
    description: "Learn about modern application development and new technologies",
    subtitle: "",
    image: "/placeholder.svg?height=200&width=400",
    color: "bg-purple-700",
    instructor: "Prof. Martinez",
    progress: 25,
  },
  {
    id: 8,
    title: "IT 374-EL3 - Integrative Programming and Technologies",
    description: "Advanced programming techniques and integration of multiple technologies",
    subtitle: "",
    image: "/placeholder.svg?height=200&width=400",
    color: "bg-gray-800",
    instructor: "Dr. Thompson",
    progress: 15,
  },
]

export const announcementData = [
  {
    id: 1,
    text: "You are required to attend the Computer Studies Life Skills Development Program",
    course: "Computer Studies Life Skills",
    date: "2025-04-10T10:30:00",
    read: false,
  },
  {
    id: 2,
    text: "CSU Piniliay is approaching",
    course: "Computer Studies Life Skills",
    date: "2025-04-08T14:15:00",
    read: false,
  },
  {
    id: 3,
    text: "Hi, Attached in the link is the Elements of Research - IT32",
    course: "Elements of Research - IT32",
    date: "2025-04-05T09:00:00",
    read: true,
  },
  {
    id: 4,
    text: "Hi everyone, For this subject Elements of Research - IT32",
    course: "Elements of Research - IT32",
    date: "2025-04-03T16:45:00",
    read: true,
  },
  {
    id: 5,
    text: "Hi, We won't have meeting today Elements of Research - IT32",
    course: "Elements of Research - IT32",
    date: "2025-04-01T08:30:00",
    read: true,
  },
]

export const assignmentData = [
  {
    id: 1,
    title: "Research Proposal",
    course: "Elements of Research - IT32",
    dueDate: "2025-04-15T23:59:00",
    status: "pending",
  },
  {
    id: 2,
    title: "Network Design Project",
    course: "Advance Networking",
    dueDate: "2025-04-18T23:59:00",
    status: "pending",
  },
  {
    id: 3,
    title: "Life Skills Reflection Paper",
    course: "Computer Studies Life Skills",
    dueDate: "2025-04-20T23:59:00",
    status: "pending",
  },
  {
    id: 4,
    title: "Summative Exam Review",
    course: "Guidelines for Taking the Summative Exams",
    dueDate: "2025-04-25T23:59:00",
    status: "pending",
  },
]
